version: "3.9"

services:
  backend:
    build: ./server
    container_name: studylink_backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
    networks:
      - myapp-net

  frontend:
    build: ./client
    container_name: studylink_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - myapp-net
    volumes:
      - ./server:/server

networks:
  myapp-net: