version: "3.9"

services:
  backend:
    build: ./server
    container_name: musical_octo_potato_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - myapp-net

  frontend:
    build: ./client
    container_name: musical_octo_potato_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - myapp-net
    volumes:
      - .:/app
      - /app/node_modules

  # db:
  #   image: postgres:16
  #   container_name: musical_octo_potato_db
  #   restart: unless-stopped
  #   environment: 
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

networks:
  myapp-net: